name = "tectop-app"
main = "worker.js"
compatibility_date = "2026-01-01"

[site]
bucket = "./"

[[d1_databases]]
binding = "DB"
database_name = "tectop-db"
database_id = "COLOQUE_O_ID_DO_SEU_D1_AQUI"

[[r2_buckets]]
binding = "MEU_BUCKET"
bucket_name = "tectop-bucket-midias"
