name = "tectop"
main = "worker.js"
compatibility_date = "2026-10-04"

[site]
bucket = "./"

[[d1_databases]]
binding = "DB"
database_name = "tectop-db"
database_id = "tectop-db"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "tectop-media-bucket"
